In [1]:
import numpy as np

In [2]:
# Tek boyutlu dizi oluşturmak için
# np.array() fonksiyonunu kullanabiliriz
# np.array() fonksiyonuna bir liste vererek
# numpy dizisi oluşturabiliriz
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# İki boyutlu ve her bir elemanı 0 olan bir dizi oluşturmak için
# np.zeros() fonksiyonunu kullanabiliriz
# np.zeros() fonksiyonuna bir tuple vererek
# boyutlari belirleyebiliriz
# Örneğin 2x2 boyutlarında bir dizi oluşturalım
zeros = np.zeros((2, 2))
zeros

array([[0., 0.],
       [0., 0.]])

In [5]:
# İki boyutlu ve her bir elemanı 1 olan bir dizi oluşturmak için
# np.ones() fonksiyonunu kullanabiliriz
# np.ones() fonksiyonuna bir tuple vererek
# boyutlari belirleyebiliriz
# Örneğin 2x2 boyutlarında bir dizi oluşturalım
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

In [6]:
# 0, n aralığında n tane elemanı olan bir dizi oluşturmak için
# np.arange() fonksiyonunu kullanabiliriz
_arange = np.arange(10)
_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 0, 10 aralığında 5 tane elemanı olan bir dizi oluşturmak için
# np.linspace() fonksiyonunu kullanabiliriz
_linspace = np.linspace(0, 10, 5)
_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# Dizi elemanlarını sıralamak için
# np.sort() fonksiyonunu kullanabiliriz
# np.sort() fonksiyonuna bir dizi vererek
# sıralanmış diziye ulaşabiliriz
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Iki tane diziyi birleştirmek için
# np.concatenate() fonksiyonunu kullanabiliriz
# np.concatenate() fonksiyonuna bir tuple vererek
# iki diziyi birleştirebiliriz
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Diziyi yeniden şekillendirmek için
# np.reshape() fonksiyonunu kullanabiliriz
_a = np.arange(6)
_a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Iki dizinin elemanlarını toplamak için
# np.add() fonksiyonunu kullanabiliriz
# np.add() fonksiyonuna iki dizi vererek
# iki dizinin elemanlarını toplayabiliriz
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.add(a, b)

array([ 6,  8, 10, 12])

In [ ]:
# Iki dizinin elemanlarını çarpmak için
# np.multiply() fonksiyonunu kullanabiliriz
# np.multiply() fonksiyonuna iki dizi vererek
# iki dizinin elemanlarını çıkarabiliriz
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.multiply(a, b)